# Generated by Django 3.1.7 on 2021-03-18 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('campeonato_id', models.AutoField(primary_key=True, serialize=False)),
                ('edicao', models.IntegerField()),
                ('data_termino', models.DateField()),
                ('campeao', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'campeonato',
                'ordering': ['edicao'],
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('time_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_time', models.CharField(max_length=100)),
                ('qt_max_jogador', models.IntegerField()),
                ('qt_atual_jogador', models.IntegerField()),
                ('num_titulo', models.IntegerField()),
                ('ativo', models.BooleanField()),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'time',
                'ordering': ['nome_time'],
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('resultado_id', models.AutoField(primary_key=True, serialize=False)),
                ('pontuacao', models.IntegerField()),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('edicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estrutura.campeonato')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estrutura.time')),
            ],
            options={
                'db_table': 'resultado',
                'ordering': ['pontuacao'],
            },
        ),
    ]
