# Generated by Django 3.1.7 on 2021-03-18 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estrutura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('jogador_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=250)),
                ('data_nascimento', models.DateField()),
                ('foto_jogador', models.ImageField(blank=True, upload_to='images/')),
                ('cpf', models.CharField(blank=True, max_length=11)),
                ('contato', models.CharField(blank=True, max_length=30)),
                ('ativo', models.BooleanField()),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estrutura.time')),
            ],
            options={
                'verbose_name_plural': 'jogadores',
                'db_table': 'jogador',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Gol',
            fields=[
                ('gol_id', models.AutoField(primary_key=True, serialize=False)),
                ('qt_gol', models.IntegerField()),
                ('tipo_gol', models.CharField(choices=[('H', 'Honra'), ('C', 'Contra')], max_length=1)),
                ('data_gol', models.DateField()),
                ('jogador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='informativo.jogador')),
            ],
            options={
                'verbose_name_plural': 'gols',
                'db_table': 'gols',
                'ordering': ['gol_id'],
            },
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('cartao_id', models.AutoField(primary_key=True, serialize=False)),
                ('qt_cartao', models.IntegerField()),
                ('tipo_cartao', models.CharField(choices=[('AMA', 'Amarelo'), ('AZL', 'Azul'), ('VRM', 'Vermelho')], max_length=3)),
                ('data_cartao', models.DateField()),
                ('jogador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='informativo.jogador')),
            ],
            options={
                'verbose_name_plural': 'cartões',
                'db_table': 'cartoes',
                'ordering': ['cartao_id'],
            },
        ),
    ]
